version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: loyalty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loyalty_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: loyalty-backend
    ports:
      - "6060:6060"
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loyalty_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data: